apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wordtex-production

resources:
  - ../base

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: sir-core
      spec:
        replicas: 5
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: latex-engine
      spec:
        replicas: 4
