apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wordtex-staging

resources:
  - ../base

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: api-gateway
      spec:
        replicas: 1
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: sir-core
      spec:
        replicas: 1
